### ISSUE TITLE
How does this work with nested tables?

### ISSUE THREAD

**Issue by vkolluri** [traf72/excel-report-generator#3]
How does this work with nested tables? I have a complex object which I want to export to excel as nested tables. Example POCO classes are shown as below:

class Company
{
    public string CompanyName { get; set; }
    public Address CompanyAddress { get; set; }
    public decimal YearSales { get; set; }
    public decimal YearProfit { get; set; }
    public List<invester> Investers { get; set; }
    public List<employee> Employees { get; set; }
}

class Investor
{
    public string InvestorName { get; set; }
    public DateTime InvestmentDate { get; set; }
    public decimal Percentage { get; set; }
}

class Employee
{
    public string EmployeeName { get; set; }
    public DateTime HiringDate { get; set; }
    public decimal Salary { get; set; }
}

class Address
{
    public int StreetNumber { get; set; }
    public string StreetName { get; set; }
    public string OfficeNumber { get; set; }
    public string CountryName { get; set; }
    public string StateName { get; set; }
    public string PostalCode { get; set; }
    public List<PhoneNumber> Telephone { get; set; }
}

class PhoneNumber
{
    public int CountryCode { get; set; }
    public int AreaCode { get; set; }
    public string PhoneNumber { get; set; }
    public int Extension { get; set; }
}

All the data is in a single c# object. I am wondering how the ExcelReportGenerator can help achieve my goal?

**Comment by traf72** [comment]
Hello!

**ExcelReportGenerator** allows you to render nested tables, including multiple ones. For this to work, you should specify the parent panel correctly. You can find a detailed explanation in the documentation starting from page 18. Additionally, there's an example called **GroupingWithPanelHierarchy** in the **ExcelReportGenerator.Samples** project that uses nested panels.

From your description, it's unclear what you want as an output result. It seems like you want to render companies to Excel, and for each company, also render all its investors and employees. To achieve this, you should use one parent panel to render companies and two child panels to render investors and employees. Since a company has only one address, we can combine it into one line and render it within the company. The same is true for phones, we can combine them and render them within the company itself. However, it's also possible to render phones as a third nested table if you wish. Taking this into account, I've arrived at this desired result:

![image](https://github.com/traf72/excel-report-generator/assets/45209977/44292ad9-28dc-43cc-8c37-95f5c6d7f183)

I've also prepared the code and the **.xlsx** template for this output result based on your description. Please, check it out, it should help.

[ExcelReportGeneratorIssue.zip](https://github.com/traf72/excel-report-generator/files/12840300/ExcelReportGeneratorIssue.zip)

**ExcelReportGenerator** is highly flexible and can render sophisticated reports. Please, read the documentation carefully and also explore the examples in the **ExcelReportGenerator.Samples** project.
